In [54]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [45]:
df = pd.read_csv(r'C:\Users\ashra\Desktop\SDBI Stuff\Sem II\ML\CODSOFTT\Datasets\Customer Churn Prediction\Churn_Modelling.csv')
print(df.head())
df=df.set_index('RowNumber')
print(df.head())
df1= df.iloc[ :,[2,4,5,6,8,11,12]]
print(df1.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [50]:
##Random Forests
rf= RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)

print('Accuracy:', accuracy_score(y_test,y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test,y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))

Accuracy: 0.8255
Confusion Matrix:
 [[1502  105]
 [ 244  149]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.86      0.93      0.90      1607
           1       0.59      0.38      0.46       393

    accuracy                           0.83      2000
   macro avg       0.72      0.66      0.68      2000
weighted avg       0.81      0.83      0.81      2000



In [48]:
## Logistic Regression
le = LabelEncoder()
df1['Gender']=le.fit_transform(df1['Gender'])

x = df1.drop('Exited',axis = 1)
y = df1['Exited']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

logreg = LogisticRegression()
logreg.fit(x_train, y_train)

y_pred = logreg.predict(x_test)

print('Accuracy:', accuracy_score(y_test,y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test,y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))

C:\Users\ashra\AppData\Local\Temp\ipykernel_38596\894556987.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Gender']=le.fit_transform(df1['Gender'])


Accuracy: 0.8
Confusion Matrix:
 [[1587   20]
 [ 380   13]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.81      0.99      0.89      1607
           1       0.39      0.03      0.06       393

    accuracy                           0.80      2000
   macro avg       0.60      0.51      0.47      2000
weighted avg       0.73      0.80      0.73      2000



C:\Users\ashra\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [56]:
##Gradient Boosting
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb.fit(x_train, y_train)
y_pred = gb.predict(x_test)

print('Accuracy:', accuracy_score(y_test,y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test,y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))

Accuracy: 0.848
Confusion Matrix:
 [[1518   89]
 [ 215  178]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.88      0.94      0.91      1607
           1       0.67      0.45      0.54       393

    accuracy                           0.85      2000
   macro avg       0.77      0.70      0.72      2000
weighted avg       0.83      0.85      0.84      2000

